server:
  port: 9999
spring:
  mvc:
    view:
      prefix: /pages/
      suffix: .jsp  datasource:    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    password: manager
    username: system  jpa:    hibernate:      ddl-auto: update    show-sql: true    properties.hibernate.format_sql: true
    properties.hibernate.dialect: org.hibernate.dialect.Oracle10gDialect